# Generated by Django 5.2.12 on 2026-05-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("sal", models.FloatField()),
                ("phone", models.PositiveBigIntegerField()),
                ("role", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("doj", models.DateField()),
            ],
        ),
    ]
