# Generated by Django 5.2.12 on 2026-05-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emp",
            name="loc",
            field=models.TextField(default="Bangalore"),
        ),
    ]
