# Generated by Django 5.2.12 on 2026-05-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("director", models.CharField(max_length=32)),
                ("description", models.TextField()),
                ("Cast", models.TextField()),
                ("budget", models.FloatField()),
                ("collections", models.FloatField()),
            ],
        ),
    ]
